# Лабораторная работа №3


In [2]:
import pandas as pd
import numpy as np
from sklearn.tree import DecisionTreeClassifier 
from sklearn import datasets
from sklearn import tree
from matplotlib import pyplot as plt
from sklearn.tree import DecisionTreeRegressor 
from sklearn import datasets
import datetime
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.preprocessing import StandardScaler
from sklearn.utils import resample
from sklearn.ensemble import BaggingClassifier
from sklearn.ensemble import BaggingRegressor
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.ensemble import GradientBoostingRegressor
from sklearn.ensemble import StackingClassifier
from sklearn.ensemble import StackingRegressor
from sklearn.metrics import mean_squared_error, mean_absolute_error, classification_report, mean_absolute_percentage_error, confusion_matrix, r2_score
from math import sqrt
from sklearn.linear_model import RidgeCV
from sklearn.svm import LinearSVR
from sklearn.svm import LinearSVC
from sklearn.pipeline import make_pipeline
from catboost import CatBoostRegressor, CatBoostClassifier
import pickle

In [8]:
data_r = pd.read_csv('../data/regression/diamonds_prepared.csv')
data_c = pd.read_csv('../data/classification/class_pred.csv')

In [9]:
data_r.drop(['Unnamed: 0'], axis=1, inplace=True)
data_r

carat  depth  table  price     x     y     z  ct_Fair  ct_Good  \
0       0.23   61.5   55.0    326  3.95  3.98  2.43        0        0   
1       0.21   59.8   61.0    326  3.89  3.84  2.31        0        0   
2       0.23   56.9   65.0    327  4.05  4.07  2.31        0        1   
3       0.29   62.4   58.0    334  4.20  4.23  2.63        0        0   
4       0.31   63.3   58.0    335  4.34  4.35  2.75        0        1   
...      ...    ...    ...    ...   ...   ...   ...      ...      ...   
53789   0.72   60.8   57.0   2757  5.75  5.76  3.50        0        0   
53790   0.72   63.1   55.0   2757  5.69  5.75  3.61        0        1   
53791   0.70   62.8   60.0   2757  5.66  5.68  3.56        0        0   
53792   0.86   61.0   58.0   2757  6.15  6.12  3.74        0        0   
53793   0.75   62.2   55.0   2757  5.83  5.87  3.64        0        0   

       ct_Ideal  ...  clr_I  clr_J  clrty_I1  clrty_IF  clrty_SI1  clrty_SI2  \
0             1  ...      0      0         0         0          0          1   
1             0  ...      0      0         0         0          1          0   
2             0  ...      0      0         0         0          0          0   
3             0  ...      1      0         0         0          0          0   
4             0  ...      0      1         0         0          0          1   
...         ...  ...    ...    ...       ...       ...        ...        ...   
53789         1  ...      0      0         0         0          1          0   
53790         0  ...      0      0         0         0          1          0   
53791         0  ...      0      0         0         0          1          0   
53792         0  ...      0      0         0         0          0          1   
53793         1  ...      0      0         0         0          0          1   

       clrty_VS1  clrty_VS2  clrty_VVS1  clrty_VVS2  
0              0          0           0           0  
1              0          0           0           0  
2              1          0           0           0  
3              0          1           0           0  
4              0          0           0           0  
...          ...        ...         ...         ...  
53789          0          0           0           0  
53790          0          0           0           0  
53791          0          0           0           0  
53792          0          0           0           0  
53793          0          0           0           0  

[53794 rows x 27 columns]

In [10]:
data_c

Airline  AirportFrom  AirportTo  DayOfWeek      Time    Length  Delay
0       0.235294     0.013699   0.037671   0.666667  0.860742  0.235115      0
1       0.470588     0.136986   0.236301   0.563097  0.521344  0.267176      0
2       0.294118     0.578767   0.219178   0.346544  0.458362  0.271756      1
3       0.647059     0.061644   0.092466   0.666667  0.399580  0.137405      1
4       0.470588     0.236301   0.047945   1.000000  0.328901  0.206107      0
...          ...          ...        ...        ...       ...       ...    ...
598233  0.588235     0.109589   0.058219   0.250316  0.801260  0.198473      1
598234  0.176471     0.089041   0.191781   0.166667  0.853744  0.160305      1
598235  1.000000     0.089041   0.116438   0.500000  0.528341  0.236641      1
598236  0.588235     0.020548   0.000000   0.000000  0.538838  0.152672      1
598237  0.117647     0.099315   0.863014   0.550680  0.538838  0.091603      1

[598238 rows x 7 columns]

In [11]:
delay_true = data_c[data_c['Delay'] == True]
delay_false = data_c[data_c['Delay'] == False]
print(delay_true.shape, delay_false.shape)

(299119, 7) (299119, 7)


In [12]:
y_c = data_c["Delay"]
X_c = data_c.drop(["Delay"], axis=1)

In [13]:
y_r = data_r["price"]
X_r = data_r.drop(["price"], axis=1)

In [14]:
X_train_r, X_test_r, y_train_r, y_test_r = train_test_split(X_r, y_r, test_size=0.2, random_state=42, shuffle=True)

In [15]:
X_train_c, X_test_c, y_train_c, y_test_c = train_test_split(X_c, y_c, test_size=0.2, random_state=42, shuffle=True, stratify=y_c)

In [16]:
scaler = StandardScaler()
X_train_r = scaler.fit_transform(X_train_r)
X_test_r = scaler.transform(X_test_r)

In [11]:
#X_train_c = pd.DataFrame(X_train_c)
#X_test_c = pd.DataFrame(X_test_c)
#y_train_c = pd.DataFrame(y_train_c)
#y_test_c = pd.DataFrame(y_test_c)
#X_train_r = pd.DataFrame(X_train_r)
#X_test_r = pd.DataFrame(X_test_r)
#y_train_r = pd.DataFrame(y_train_r)
#y_test_r = pd.DataFrame(y_test_r)
#X_train_c.to_csv("../data/classification/X_train_c.csv")
#X_test_c.to_csv("../data/classification/X_test_c.csv")
#y_train_c.to_csv("../data/classification/y_train_c.csv")
#y_test_c.to_csv("../data/classification/y_test_c.csv")
#X_train_r.to_csv("../data/regression/X_train_r.csv")
#X_test_r.to_csv("../data/regression/X_test_r.csv")
#y_train_r.to_csv("../data/regression/y_train_r.csv")
#y_test_r.to_csv("../data/regression/y_test_r.csv")

In [211]:
parameters = {'max_depth': [i for i in range(1, 24)]}
dtr_optimal = GridSearchCV(DecisionTreeRegressor(max_features='auto'), parameters).fit(X_train_r, y_train_r)
dtr_optimal.best_params_

c:\OmSTU\Python\ml\venv\lib\site-packages\sklearn\tree\_classes.py:277: FutureWarning: `max_features='auto'` has been deprecated in 1.1 and will be removed in 1.3. To keep the past behaviour, explicitly set `max_features=1.0'`.
  warnings.warn(
c:\OmSTU\Python\ml\venv\lib\site-packages\sklearn\tree\_classes.py:277: FutureWarning: `max_features='auto'` has been deprecated in 1.1 and will be removed in 1.3. To keep the past behaviour, explicitly set `max_features=1.0'`.
  warnings.warn(
c:\OmSTU\Python\ml\venv\lib\site-packages\sklearn\tree\_classes.py:277: FutureWarning: `max_features='auto'` has been deprecated in 1.1 and will be removed in 1.3. To keep the past behaviour, explicitly set `max_features=1.0'`.
  warnings.warn(
c:\OmSTU\Python\ml\venv\lib\site-packages\sklearn\tree\_classes.py:277: FutureWarning: `max_features='auto'` has been deprecated in 1.1 and will be removed in 1.3. To keep the past behaviour, explicitly set `max_features=1.0'`.
  warnings.warn(
c:\OmSTU\Python\ml\v

KeyboardInterrupt: 

In [7]:
dtr = DecisionTreeRegressor(max_depth=13, max_features='auto')
dtr.fit(X_train_r, y_train_r)
#y_pred_r = dtr.predict(X_test_r)
#text_representation = tree.export_text(dtr)
#print(text_representation)

c:\OmSTU\Python\ml\venv\lib\site-packages\sklearn\tree\_classes.py:277: FutureWarning: `max_features='auto'` has been deprecated in 1.1 and will be removed in 1.3. To keep the past behaviour, explicitly set `max_features=1.0'`.
  warnings.warn(


DecisionTreeRegressor(max_depth=13, max_features='auto')

In [ ]:
def Metrics(y_test, y_pred, X_test, f):
    print(f'MAE: {mean_absolute_error(y_test, y_pred)}')
    print(f'MSE: {mean_squared_error(y_test, y_pred)}')
    print(f'RMSE: {sqrt(mean_squared_error(y_test, y_pred))}')
    print(f'MAPE: {(mean_absolute_percentage_error(y_test, y_pred))}')
    print(f'R^2: {f.score(X_test, y_test)}')

Metrics(y_test_r, y_pred_r, X_test_r, dtr)

MAE: 330.6936611924138
MSE: 406889.3053165425
RMSE: 637.878754401291
MAPE: 0.30277629116817556
R^2: 0.9733048529839122


In [ ]:
dtс_optimal = GridSearchCV(DecisionTreeClassifier(max_features='auto'), parameters).fit(X_train_c, y_train_c)
dtс_optimal.best_params_

c:\OmSTU\Python\ml\venv\lib\site-packages\sklearn\tree\_classes.py:269: FutureWarning: `max_features='auto'` has been deprecated in 1.1 and will be removed in 1.3. To keep the past behaviour, explicitly set `max_features='sqrt'`.
  warnings.warn(
c:\OmSTU\Python\ml\venv\lib\site-packages\sklearn\tree\_classes.py:269: FutureWarning: `max_features='auto'` has been deprecated in 1.1 and will be removed in 1.3. To keep the past behaviour, explicitly set `max_features='sqrt'`.
  warnings.warn(
c:\OmSTU\Python\ml\venv\lib\site-packages\sklearn\tree\_classes.py:269: FutureWarning: `max_features='auto'` has been deprecated in 1.1 and will be removed in 1.3. To keep the past behaviour, explicitly set `max_features='sqrt'`.
  warnings.warn(
c:\OmSTU\Python\ml\venv\lib\site-packages\sklearn\tree\_classes.py:269: FutureWarning: `max_features='auto'` has been deprecated in 1.1 and will be removed in 1.3. To keep the past behaviour, explicitly set `max_features='sqrt'`.
  warnings.warn(
c:\OmSTU\Pyt

{'max_depth': 21}

In [10]:
dtc = DecisionTreeClassifier(max_depth=21, max_features='auto')
dtc.fit(X_train_c, y_train_c)
y_pred_c = dtc.predict(X_test_c)
text_representation = tree.export_text(dtc)
print(text_representation)

NameError: name 'X_train_c' is not defined

In [ ]:
print(classification_report(y_test_c, y_pred_c))
print(confusion_matrix(y_test_c, y_pred_c))

              precision    recall  f1-score   support

           0       0.50      0.52      0.51     59824
           1       0.50      0.48      0.49     59824

    accuracy                           0.50    119648
   macro avg       0.50      0.50      0.50    119648
weighted avg       0.50      0.50      0.50    119648

[[30886 28938]
 [31118 28706]]


In [ ]:
parameters = {'n_estimators': [i for i in range(10, 21)]}
bag_r_optimal = GridSearchCV(BaggingRegressor(), parameters).fit(X_train_r, y_train_r)
bag_r_optimal.best_params_

{'n_estimators': 19}

In [11]:
bag_r = BaggingRegressor(random_state=42, n_estimators=19).fit(X_train_r, y_train_r)
#y_pred_bag_r = bag_r.predict(X_test_r)

In [ ]:
Metrics(y_test_r, y_pred_bag_r, X_test_r, bag_r)

MAE: 270.69299672408084
MSE: 290403.89198087103
RMSE: 538.891354524148
MAPE: 0.2589660349260379
R^2: 0.9809472146621243


In [ ]:
bag_c_optimal = GridSearchCV(BaggingClassifier(), parameters).fit(X_train_c, y_train_c)
bag_c_optimal.best_params_

{'n_estimators': 12}

In [ ]:
bag_c = BaggingClassifier(random_state=42, n_estimators=12).fit(X_train_c, y_train_c)
y_pred_bag_c = bag_c.predict(X_test_c)

In [ ]:
print(classification_report(y_test_c, y_pred_bag_c))
print(confusion_matrix(y_test_c, y_pred_bag_c))

              precision    recall  f1-score   support

           0       0.50      0.52      0.51     59824
           1       0.50      0.48      0.49     59824

    accuracy                           0.50    119648
   macro avg       0.50      0.50      0.50    119648
weighted avg       0.50      0.50      0.50    119648

[[30984 28840]
 [31076 28748]]


In [ ]:
parameters = {'alpha': [float(i)/100 for i in range(10, 100, 10)]}
grad_boost_r_optimal = GridSearchCV(GradientBoostingRegressor(), parameters).fit(X_train_r, y_train_r)
grad_boost_r_optimal.best_params_

c:\OmSTU\Python\ml\venv\lib\site-packages\sklearn\model_selection\_validation.py:378: FitFailedWarning: 
5 fits failed out of a total of 50.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
5 fits failed with the following error:
Traceback (most recent call last):
  File "c:\OmSTU\Python\ml\venv\lib\site-packages\sklearn\model_selection\_validation.py", line 686, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "c:\OmSTU\Python\ml\venv\lib\site-packages\sklearn\ensemble\_gb.py", line 420, in fit
    self._validate_params()
  File "c:\OmSTU\Python\ml\venv\lib\site-packages\sklearn\base.py", line 581, in _validate_params
    validate_parameter_constraints(
  File "c:\OmSTU\Python\ml\venv\lib\site-packages\sklearn\u

{'alpha': 0.3}

In [ ]:
grad_boost_r = GradientBoostingRegressor(random_state=42, alpha=0.3)
grad_boost_r.fit(X_train_r, y_train_r)
y_pred_grad_r = grad_boost_r.predict(X_test_r)

In [ ]:
Metrics(y_test_r, y_pred_grad_r, X_test_r, grad_boost_r)

MAE: 400.06961904638524
MSE: 520179.2199465645
RMSE: 721.2345110618076
MAPE: 0.35734192719810853
R^2: 0.9658721412193804


In [ ]:
parameters = {'max_depth': [i for i in range(1, 6)]}
grad_boost_r_optimal = GridSearchCV(GradientBoostingClassifier(), parameters).fit(X_train_c, y_train_c)
grad_boost_r_optimal.best_params_

{'max_depth': 5}

In [ ]:
grad_boost_c = GradientBoostingClassifier(random_state=42, max_depth=5)
grad_boost_c.fit(X_train_c, y_train_c)
y_pred_grad_c = grad_boost_c.predict(X_test_c)

In [ ]:
print(classification_report(y_test_c, y_pred_grad_c))
print(confusion_matrix(y_test_c, y_pred_grad_c))

              precision    recall  f1-score   support

           0       0.50      0.49      0.50     59824
           1       0.50      0.51      0.50     59824

    accuracy                           0.50    119648
   macro avg       0.50      0.50      0.50    119648
weighted avg       0.50      0.50      0.50    119648

[[29427 30397]
 [29498 30326]]


In [ ]:
estimators = [('lr', RidgeCV()),('svr', LinearSVR(random_state=42))]

stack_r = StackingRegressor(estimators = estimators)
stack_r.fit(X_train_r, y_train_r)
y_pred_stack_r = stack_r.predict(X_test_r)

Metrics(y_test_r, y_pred_grad_r, X_test_r, stack_r)

MAE: 400.06961904638524
MSE: 520179.2199465645
RMSE: 721.2345110618076
MAPE: 0.35734192719810853
R^2: 0.9202796099997986


In [ ]:
estimators = [
    ('b', BaggingClassifier(n_estimators=12, random_state=42)),
    ('svr', make_pipeline(StandardScaler(),
    LinearSVC(random_state=42)))]

stack_c = StackingClassifier(estimators = estimators)
stack_c.fit(X_train_c, y_train_c)
y_pred_stack_c = stack_c.predict(X_test_c)

print(classification_report(y_test_c, y_pred_stack_c))
print(confusion_matrix(y_test_c, y_pred_grad_c))

c:\OmSTU\Python\ml\venv\lib\site-packages\sklearn\svm\_base.py:1244: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
c:\OmSTU\Python\ml\venv\lib\site-packages\sklearn\svm\_base.py:1244: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
c:\OmSTU\Python\ml\venv\lib\site-packages\sklearn\svm\_base.py:1244: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
c:\OmSTU\Python\ml\venv\lib\site-packages\sklearn\svm\_base.py:1244: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
c:\OmSTU\Python\ml\venv\lib\site-packages\sklearn\svm\_base.py:1244: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
c:\OmSTU\Python\ml\venv\lib\site-packages\sklearn\svm\_base.py:1244: ConvergenceWarning: Liblinear failed to converge, increase the number of ite

              precision    recall  f1-score   support

           0       0.50      0.02      0.04     59824
           1       0.50      0.98      0.66     59824

    accuracy                           0.50    119648
   macro avg       0.50      0.50      0.35    119648
weighted avg       0.50      0.50      0.35    119648

[[29427 30397]
 [29498 30326]]


In [223]:
cat_r = CatBoostRegressor(iterations=2,
                          learning_rate=1,
                          depth=2)
cat_r.fit(X_train_r, y_train_r)
y_pred_cat_r = cat_r.predict(X_test_r)
Metrics(y_test_r, y_pred_cat_r, X_test_r, cat_r)

0:	learn: 1916.8076458	total: 3.73ms	remaining: 3.73ms
1:	learn: 1727.9624973	total: 7.3ms	remaining: 0us
MAE: 1078.082684036831
MSE: 2881140.681274984
RMSE: 1697.3923180204936
MAPE: 0.5505174023025305
R^2: 0.8109744516365887


In [222]:
cat_c = CatBoostClassifier(iterations=100,
                           depth=4)
cat_c.fit(X_train_c, y_train_c)
y_pred_cat_c = cat_c.predict(X_test_c)

print(classification_report(y_test_c, y_pred_cat_c))
print(confusion_matrix(y_test_c, y_pred_cat_c))

Learning rate set to 0.5
0:	learn: 0.6931284	total: 22ms	remaining: 2.18s
1:	learn: 0.6931412	total: 41.3ms	remaining: 2.02s
2:	learn: 0.6931200	total: 60.2ms	remaining: 1.95s
3:	learn: 0.6930948	total: 79.4ms	remaining: 1.9s
4:	learn: 0.6930823	total: 96.6ms	remaining: 1.83s
5:	learn: 0.6930639	total: 112ms	remaining: 1.76s
6:	learn: 0.6930437	total: 130ms	remaining: 1.73s
7:	learn: 0.6930262	total: 150ms	remaining: 1.72s
8:	learn: 0.6930152	total: 166ms	remaining: 1.68s
9:	learn: 0.6929990	total: 182ms	remaining: 1.64s
10:	learn: 0.6929993	total: 199ms	remaining: 1.61s
11:	learn: 0.6929861	total: 219ms	remaining: 1.6s
12:	learn: 0.6929686	total: 237ms	remaining: 1.59s
13:	learn: 0.6929631	total: 257ms	remaining: 1.58s
14:	learn: 0.6929552	total: 278ms	remaining: 1.58s
15:	learn: 0.6929474	total: 298ms	remaining: 1.56s
16:	learn: 0.6929421	total: 317ms	remaining: 1.55s
17:	learn: 0.6929274	total: 337ms	remaining: 1.53s
18:	learn: 0.6929130	total: 357ms	remaining: 1.52s
19:	learn: 0.69

In [63]:
class Node:
    def __init__(self, data):
        self.left = None
        self.right = None
        self.feature = None
        self.threshold = None
        self.data = data
        self.m = 0

In [62]:
def best_params_r(data):
    ftr = data.columns[0]
    trsld = data[ftr].unique()[0]
    err = data[data[ftr] <= trsld].iloc[:, -1].std() + data[data[ftr] > trsld].iloc[:, -1].std()
    for f in data.iloc[:, :-1].columns:
        for t in data[f].unique():
            e = data[data[f] <= t].iloc[:, -1].std() + data[data[f]  > t].iloc[:, -1].std()
            if e < err:
                err = e
                ftr = f
                trsld = t
    return ftr, trsld

def best_params_c(data):
    ftr = data.columns[0]
    trsld = data[ftr].unique()[0]
    d = data[data[ftr] <= trsld]
    m = d.iloc[:, -1].mode()[0]
    per = d[d.iloc[:, -1] == m].shape[0] / d.shape[0]
    for f in data.iloc[:, :-1].columns:
        for t in data[f].unique():
            d = data[data[f] <= t]
            m = d.iloc[:, -1].mode()[0]
            p = d[d.iloc[:, -1] == m].shape[0] / d.shape[0]
            if p > per:
                per = p
                ftr = f
                trsld = t
    return ftr, trsld

In [61]:
def Rec_Tree(data, n, type, len):
    node = Node(data)
    print(data.shape[0])
    if data.shape[0] <= n or data.shape[0] == len:
        if type == 'r':
            node.m = node.data.iloc[:, -1].mean()
        if type == 'c':
            node.m = node.data.iloc[:, -1].mode()[0]
        return node
    else:
        if type == 'r':
            f, t = best_params_r(data)
            node.feature = f
            node.threshold = t
            node.left = Rec_Tree(data[data[f] <= t], n, 'r', data.shape[0])
            node.right = Rec_Tree(data[data[f] > t], n, 'r', data.shape[0])
        if type == 'c':
            f, t = best_params_c(data)
            node.feature = f
            node.threshold = t
            if data[data[f] <= t].shape[0] != 0:
                node.left = Rec_Tree(data[data[f] <= t], n, 'c', data.shape[0])
            else:
                return node
            if data[data[f] > t].shape[0] != 0:
                node.right = Rec_Tree(data[data[f] > t], n, 'c', data.shape[0])
            else:
                return node
        return node

In [73]:
class Tree:
    def __init__(self):
        pass
    def fit_r(self, X, y, n=100):
        data = pd.concat([pd.DataFrame(X).reset_index(drop=True), pd.DataFrame(y).reset_index(drop=True)], axis=1)
        self.Tree_r = Rec_Tree(data, n, 'r', data.shape[0] + 1)
    def fit_c(self, X, y, n=100):
        data = pd.concat([pd.DataFrame(X).reset_index(drop=True), pd.DataFrame(y).reset_index(drop=True)], axis=1)
        self.Tree_c = Rec_Tree(data, n, 'c', data.shape[0] + 1)
    def predict_r(self, X):
        y_pred = []
        X = pd.DataFrame(X)
        X = X.reset_index(drop=True)
        for i in range(X.shape[0]):
            cur_node = self.Tree_r
            while cur_node.left != None or cur_node.right != None:
                if X[cur_node.feature][i] <= cur_node.threshold:
                    cur_node = cur_node.left
                else:
                    cur_node = cur_node.right
            y_pred.append(cur_node.m)
        return np.array(y_pred)
    def predict_c(self, X):
        y_pred = []
        X = pd.DataFrame(X)
        X = X.reset_index()
        for i in range(X.shape[0]):
            cur_node = self.Tree_c
            while cur_node.left != None or cur_node.right != None:
                if X[cur_node.feature][i] <= cur_node.threshold:
                    cur_node = cur_node.left
                else:
                    cur_node = cur_node.right
            y_pred.append(cur_node.m)
        return np.array(y_pred)


In [74]:
tree = Tree()
tree.fit_r(X_train_r[:10000], y_train_r[:10000], 500)

10000
4
9996
62
9934
56
9878
177
9701
26
9675
2
9673
464
9209
406
8803
345
8458
207
8251
182
8069
251
7818
1011
1007
1005
1001
998
993
3
990
985
8
977
973
2
971
2
969
881
879
682
2
680
2
678
3
675
3
672
646
638
5
633
445
188
8
26
197
2
88
4
5
5
3
4
2
4
6807
65
6742
34
6708
643
641
639
636
569
4
565
555
401
154
10
67
3
2
2
6065
414
5651
181
5470
1098
1096
1094
1087
1082
3
1079
3
1076
9
1067
3
1064
3
1061
1058
1005
1002
997
3
994
971
968
946
943
934
10
924
782
776
774
770
9
761
759
19
740
3
737
659
630
2
628
618
14
604
595
399
196
9
10
29
78
2
4
2
6
142
9
3
22
3
23
5
3
53
3
5
7
2
2
4372
153
4219
180
4039
134
3905
337
3568
4
3564
5
3559
3
3556
37
3519
9
3510
3
3507
8
3499
3489
16
3473
21
3452
3
3449
219
3230
3
3227
3
3224
5
3219
3
3216
3208
151
3057
2
3055
65
2990
81
2909
1709
1666
1664
2
1662
1654
1531
1151
1145
1142
1139
1110
745
740
650
648
642
3
639
637
634
5
629
515
3
512
4
508
310
198
114
3
2
6
2
90
5
365
29
3
3
6
380
123
8
2
43
1200
2
1198
1173
1171
1168
1166
1161
1159
1118
1116
3


In [75]:
y_pred = tree.predict_r(X_test_r)

In [76]:
print(f'MAE: {mean_absolute_error(y_test_r, y_pred)}')
print(f'MSE: {mean_squared_error(y_test_r, y_pred)}')
print(f'RMSE: {sqrt(mean_squared_error(y_test_r, y_pred))}')
print(f'R2': {r2_score(y_test_r, y_pred)})
print(f'MAPE: {(mean_absolute_percentage_error(y_test_r, y_pred))}')

MAE: 637.9735725260982
MSE: 1316045.4642473003
RMSE: 1147.1902476256064
MAPE: 0.1727965359475467


In [77]:
tree1 = Tree()
tree1.fit_c(X_train_c[:1000], y_train_c[:1000])

1000
1
999
1
998
1
997
1
996
1
995
3
992
1
991
8
983
6
977
3
974
9
965
28
937
56
881
45
836
13
823
25
798
20
778
1
777
2
775
3
772
1
771
1
770
1
769
5
764
58
706
1
705
1
704
2
702
1
701
1
700
2
698
1
697
2
695
1
694
2
692
3
689
1
688
1
687
18
669
21
648
83
565
2
563
1
562
6
556
1
555
8
547
9
538
6
532
1
531
1
530
5
525
3
522
7
515
13
502
2
500
3
497
1
496
23
473
2
471
1
470
11
459
3
456
1
455
2
453
3
450
1
449
3
446
5
441
3
438
2
436
1
435
7
428
4
424
7
417
1
416
21
395
10
385
18
367
28
339
1
338
25
313
5
308
1
307
8
299
1
298
1
297
1
296
1
295
2
293
1
292
1
291
4
287
5
282
4
278
6
272
1
271
2
269
7
262
11
251
11
240
6
234
2
232
8
224
4
220
2
218
8
210
8
202
2
200
1
199
2
197
10
187
10
177
20
157
2
155
3
152
1
151
9
142
1
141
2
139
1
138
1
137
1
136
2
134
1
133
4
129
1
128
5
123
2
121
1
120
1
119
9
110
1
109
1
108
23
85


In [80]:
y_pred_c = tree1.predict_c(X_test_c)

In [81]:
print(classification_report(y_test_c, y_pred_c))

              precision    recall  f1-score   support

           0       0.50      0.50      0.50     59824
           1       0.50      0.50      0.50     59824

    accuracy                           0.50    119648
   macro avg       0.50      0.50      0.50    119648
weighted avg       0.50      0.50      0.50    119648



In [82]:
print(confusion_matrix(y_test_c, y_pred_c))

[[30158 29666]
 [29830 29994]]
